#!/usr/bin/env bash
set -euo pipefail
[[ "${PACKAGE_AK3:-false}" == true ]] || { echo '[+] AnyKernel3 packaging disabled'; exit 0; }
cd "${KERNEL_ROOT:?}"; out=${OUT_DIR:-out}; artifact=${ARTIFACT_DIR:?}; git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git "$artifact/AnyKernel3"
ak="$artifact/AnyKernel3"; slot=0; [[ "${AB_PARTITION:-false}" == true ]] && slot=1
cat > "$ak/anykernel.sh" <<EOF
### AnyKernel3 Ramdisk Mod Script
## Generated by SukiSU Non-GKI workflow

### AnyKernel setup
## global properties
properties() { '
kernel.string=${CODENAME:?} SukiSU+Susfs集成内核 by${AUTHOR:-XiZi}
do.devicecheck=1
do.modules=0
do.systemless=0
do.cleanup=1
do.cleanuponabort=0
device.name1=${CODENAME}
device.name2=
supported.versions=
supported.patchlevels=
supported.vendorpatchlevels=
'; } # end properties

### AnyKernel install
## boot files attributes
boot_attributes() {
  set_perm_recursive 0 0 755 644 \$RAMDISK/*;
  set_perm_recursive 0 0 750 750 \$RAMDISK/init* \$RAMDISK/sbin;
} # end attributes

## boot shell variables
BLOCK=boot;
IS_SLOT_DEVICE=$slot;
RAMDISK_COMPRESSION=auto;
PATCH_VBMETA_FLAG=auto;

## import functions/variables and setup patching
. tools/ak3-core.sh;

## custom build information
ui_print "内核版本:${KERNEL_NAME:-by_XiZi}";

## boot install
dump_boot;
write_boot;
## end boot install
EOF
cp "$out/arch/${ARCH:-arm64}/boot/${BUILD_TARGET:-Image.gz-dtb}" "$ak/"
printf '%s SukiSU+Susfs集成内核 by%s\n内核版本:%s\n' "$CODENAME" "${AUTHOR:-XiZi}" "${KERNEL_NAME:-by_XiZi}" > "$ak/README_FLASH.txt"
(cd "$ak" && zip -qr "$artifact/${CODENAME}-SukiSU-Non-GKI-AK3.zip" .)
