#!/usr/bin/env bash
set -euo pipefail
[[ "${PACKAGE_AK3:-false}" == true ]] || { echo '[+] AnyKernel3 packaging disabled'; exit 0; }
cd "${KERNEL_ROOT:?}"; out=${OUT_DIR:-out}; artifact=${ARTIFACT_DIR:?}
ak3_target=${AK3_KERNEL_TARGET:-${BUILD_TARGET:-Image.gz-dtb}}
case "$ak3_target" in
  Image.gz|Image.gz-dtb) ;;
  *) echo "[ERROR] unsupported AnyKernel3 kernel target: $ak3_target" >&2; exit 1 ;;
esac
kernel_image="$out/arch/${ARCH:-arm64}/boot/$ak3_target"
[[ -f "$kernel_image" ]] || { echo "[ERROR] AnyKernel3 kernel target is missing: $kernel_image" >&2; exit 1; }
git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git "$artifact/AnyKernel3"
# Let AnyKernel3 resolve the slot on the device at install time.  A hard-coded
# 0/1 here is unsafe because the workflow input describes the source package,
# while the actual boot slot is a property of the target device.  `auto` uses
# the active slot on A/B devices and falls back to the unsuffixed boot
# partition on legacy devices.
ak="$artifact/AnyKernel3"; slot_mode=auto
if [[ -n "${GITHUB_ENV:-}" ]]; then printf 'AK3_SLOT_MODE=%s\n' "$slot_mode" >> "$GITHUB_ENV"; fi
cat > "$ak/anykernel.sh" <<EOF
### AnyKernel3 Ramdisk Mod Script
## Generated by SukiSU Non-GKI workflow

### AnyKernel setup
## global properties
properties() { '
kernel.string=${CODENAME:?} SukiSU+Susfs集成内核 by${AUTHOR:-XiZi}
do.devicecheck=1
do.modules=0
do.systemless=0
do.cleanup=1
do.cleanuponabort=0
device.name1=${CODENAME}
device.name2=
supported.versions=
supported.patchlevels=
supported.vendorpatchlevels=
'; } # end properties

### AnyKernel install
## boot files attributes
boot_attributes() {
  set_perm_recursive 0 0 755 644 \$RAMDISK/*;
  set_perm_recursive 0 0 750 750 \$RAMDISK/init* \$RAMDISK/sbin;
} # end attributes

## boot shell variables
BLOCK=boot;
IS_SLOT_DEVICE=$slot_mode;
SLOT_SELECT=active;
RAMDISK_COMPRESSION=auto;
PATCH_VBMETA_FLAG=auto;

## import functions/variables and setup patching
. tools/ak3-core.sh;

## custom build information
ui_print "内核版本:${KERNEL_NAME:-by_XiZi}";

## boot install
dump_boot;
write_boot;
## end boot install
EOF
cp "$kernel_image" "$ak/"
if [[ -n "${GITHUB_ENV:-}" ]]; then printf 'AK3_KERNEL_TARGET=%s\n' "$ak3_target" >> "$GITHUB_ENV"; fi
printf '%s SukiSU+Susfs集成内核 by%s\n内核版本:%s\n' "$CODENAME" "${AUTHOR:-XiZi}" "${KERNEL_NAME:-by_XiZi}" > "$ak/README_FLASH.txt"
printf 'AK3 slot mode: %s (workflow AB_PARTITION=%s; resolved on device)\n' "$slot_mode" "${AB_PARTITION:-false}" >> "$ak/README_FLASH.txt"
(cd "$ak" && zip -qr "$artifact/${CODENAME}-SukiSU-Non-GKI-AK3.zip" .)
